### ISSUE TITLE
So good information.

### ISSUE THREAD

**Issue by hongsoonchul** [nexmo-community/python-voicemail-dead-drop#3]
There is one problem.
"Call From:"
"When:"
Two pieces of information do not appear correctly.

I tested it on windows 7.
The authentication source is hard coded.
Help. My teacher ...

**Comment by superdiana** [comment]
Hello @hongsoonchul ! you can find the step by step tutorial to build this with all the required information: [https://www.nexmo.com/blog/2019/04/05/how-to-build-a-voicemail-with-python-flask-dr](https://www.nexmo.com/blog/2019/04/05/how-to-build-a-voicemail-with-python-flask-dr) .
